add UNNC
mtf-wiki/RLE-wiki pull request #49
Opened 2022-09-13 01:40 UTC by kawaai-hina

2022-09-13 05:25 UTC, ArtsEpiphany requested changes
啊这...首先页面头部不是这样子写的，你可以看看其他页面的开头...还有为什么要用全角呀...稍等我慢慢改吧

2022-09-13 05:25 UTC, ArtsEpiphany commented
Anyway，感谢提交pr！

2022-09-13 23:53 UTC, kawaai-hina commented
qwq

2022-09-15 00:44 UTC, septs commented on docs/campus/UNNC.md
> +date: 2022-09-13 09:40:00
```suggestion
```

2022-09-15 00:44 UTC, septs commented on docs/campus/UNNC.md
> +注意：这篇文章写的时候（2022年9月13日），学校周边有路段施工，注意不要迷路了。
```suggestion
```

具有强烈时效性

2022-09-15 00:45 UTC, septs commented on docs/campus/UNNC.md
> +配置有空调，有线网络端口，Wifi 24小时全覆盖，24小时热水，上床下桌，蚊帐架，爬梯，衣柜，立柜凳子，储物柜，盥洗台，独立卫生间淋浴间，窗帘。自带床上用品，包括床垫。
```suggestion
配置有空调，有线网络端口，WiFi 全覆盖，全天热水，上床下桌，蚊帐架，爬梯，衣柜，立柜凳子，储物柜，盥洗台，独立卫生间淋浴间，窗帘。自带床上用品，包括床垫。
```

2022-09-15 00:45 UTC, septs commented on docs/campus/UNNC.md
> +住宿费：3000元每人学年。
```suggestion
住宿费：3000元/每人/学年。
```

2022-09-15 00:46 UTC, septs commented on docs/campus/UNNC.md
> +配置有空调，有线网络端口，Wifi 24小时全覆盖，24小时热水，上床下桌，蚊帐架，爬梯，衣柜，立柜凳子，储物柜，盥洗台，独立卫生间淋浴间，窗帘。自带床上用品，包括床垫。
房型 应当合并陈述

DON'T REPEAT YOURSELF

2022-10-16 10:32 UTC, ArtsEpiphany approved these changes
感谢提交pr！

住宿好复杂诶...

2022-10-16 10:35 UTC, merged