Update info about BJTU
mtf-wiki/RLE-wiki pull request #69
Opened 2022-10-27 05:23 UTC by wychlw

2022-10-27 12:40 UTC, Rinfair-CSP-A016 requested changes
建议根据贡献指南补充有关细节，若不确定可保持TODO标记

2022-10-27 12:40 UTC, Rinfair-CSP-A016 commented on docs/campus/BJTU.md
> +关于免修：目前规则较为严格，需要学校、校医院同意之后，转入保健班。
免修免训需要学校、校医院同意的高校很多，能否具体阐述相关流程（例如易性症/性别不一致诊断等相关文件是否能用于申请免训等）

2022-10-27 12:40 UTC, Rinfair-CSP-A016 commented on docs/campus/BJTU.md
> +关于体测：体测**计入学分**，每年0.5分，过60分能拿。
体测是否严格，有没有可能因身体情况等有关原因申请免测？
（建议根据贡献指南补充信息）

2022-10-27 12:40 UTC, Rinfair-CSP-A016 commented on docs/campus/BJTU.md
> +、
```suggestion

```
？

2022-10-27 12:40 UTC, Rinfair-CSP-A016 commented on docs/campus/BJTU.md
> +> 六人间，有独立卫浴。有单独衣柜。床铺够高可以挂窗帘（但是会扣宿舍评分。不过，不想拿五星宿舍可以忽略）
```suggestion
> 六人间，有独立卫浴，有单独衣柜。床铺够高可以挂床帘（但是会扣宿舍评分。不过，不想拿五星宿舍可以忽略）
```

2022-10-27 12:40 UTC, Rinfair-CSP-A016 commented on docs/campus/BJTU.md
> +> 床铺预分配，禁止调换。由于北京市政策，必须住校。
```suggestion

```

2022-10-27 13:37 UTC, wychlw commented on docs/campus/BJTU.md
> +关于免修：目前规则较为严格，需要学校、校医院同意之后，转入保健班。
直接易性症/性别不一致诊断等相关文件不太行。审核还是比较严的。
流程直接在系统上提交免体申请与三甲医院诊断即可。

2022-10-27 13:37 UTC, wychlw commented on docs/campus/BJTU.md
> +关于体测：体测**计入学分**，每年0.5分，过60分能拿。
身体原因仅有不适宜剧烈运动的如呼吸道疾病、心血管疾病、关节疾病等。

体测降低标准不可能，全部机器统一测试。
体育课视老师而定。（但是一般也不会允许）

2022-10-28 10:26 UTC, Rinfair-CSP-A016 approved these changes
Require format & edit

2022-11-29 07:02 UTC, Cryolitia approved these changes

2022-12-05 09:36 UTC, closed without merging