Update HQU.md
mtf-wiki/RLE-wiki pull request #78
Opened 2022-11-28 12:05 UTC by NoiraBaka

Signed-off-by: NoiraBaka <119305926+NoiraBaka@users.noreply.github.com>

2022-11-29 06:57 UTC, Cryolitia requested changes

2022-11-29 06:57 UTC, Cryolitia commented on docs/campus/HQU.md
> +- 就我所知计算机学院的几个辅导员对MtF都比较友好
```suggestion
> 就我所知计算机学院的几个辅导员对MtF都比较友好
```

2022-11-29 08:24 UTC, Cryolitia approved these changes

2022-11-29 09:06 UTC, ArtsEpiphany reviewed
感谢提交pr！请注意：

1. 凡是出现「我」「笔者」字样，以及出现大量主观叙述（如「训练强度中规中矩」等）的页面强烈建议署名
2. RLE Wiki希望为所有跨性别者提供帮助，因此如果你相信计算机学院的辅导员是Trans友好的而不仅仅是MtF友好的，则尽量使用Trans代替MtF
3. 其他人也可能参与页面的编辑，如果你有长期维护此页面的意愿，请对项目保持关注

2022-11-29 18:47 UTC, Cryolitia approved these changes

2022-12-08 07:43 UTC, ArtsEpiphany requested changes
最关键的问题是...你怎么把目录名都汉化了...这样会炸的...

2022-12-08 07:43 UTC, ArtsEpiphany commented on 文档/校园/HQU.md
> +date: 2022-12-8 15:00:00
```suggestion
date: 2022-12-08 15:00:00
```

2022-12-08 07:43 UTC, ArtsEpiphany commented on 文档/校园/HQU.md
> +- 军训为期两周，训练强度即使是把cism的标准套在cisf身上也算中规中矩
```suggestion
- 军训为期两周，训练强度即使是把 CisM 的标准套在 CisF 身上也算中规中矩
```

2022-12-08 07:43 UTC, ArtsEpiphany commented on 文档/校园/HQU.md
> +- 倒是可以拍X光，不确定能否拍乳腺CT
```suggestion
- 厦门校区的校医院主要是诊所性质的，只能看一些常见病，并不能检查激素六项，也无法买到 HRT 药物
- 倒是可以拍 X 光，不确定能否拍乳腺 CT
```

2022-12-08 07:45 UTC, Cryolitia commented on 文档/校园/HQU.md
> +- 军训为期两周，训练强度即使是把cism的标准套在cisf身上也算中规中矩
https://mtf.wiki/zh-cn/docs/useful-info/abbreviation/ 里面写的是小写c大写M/F
挠头.jpg

2022-12-08 07:46 UTC, ArtsEpiphany commented
就...你必须把文件放在“docs/campus”下面，而不是“文档/校园”下面

2022-12-08 07:55 UTC, NoiraBaka commented
> 最关键的问题是...你怎么把目录名都汉化了...这样会炸的...

2022-12-08 07:59 UTC, NoiraBaka commented
可恶，完全不会用

2022-12-08 08:16 UTC, Rinfair-CSP-A016 commented
问题已解决（笑

2022-12-08 08:20 UTC, NoiraBaka commented
很可惜我在此之前从未使用过github
英语水平也一塌糊涂
我是假的前oier

2022-12-08 08:24 UTC, Rinfair-CSP-A016 commented
> 我是假的前oier

谁说oier一定要会用GitHub了（笑
各有所长不是挺好的吗，你让我去打oi我也打不来的

2022-12-08 08:25 UTC, NoiraBaka commented
> > 我是假的前oier
> 
> 谁说oier一定要会用GitHub了（笑 各有所长不是挺好的吗，你让我去打oi我也打不来的

无所谓，反正我也没拿到任何名次
不过github我的确不会用就是了，并且担心会不会有后来编辑者也不会用

2022-12-08 08:28 UTC, Cryolitia commented
>不过github我的确不会用就是了，并且担心会不会有后来编辑者也不会用

不会用GitHub的话其实可以邮件甚至QQ投稿的，交流和修改也都可以在任意能联系到mantainer的平台上进行

2022-12-10 16:37 UTC, NoiraBaka commented
还需要我做什么吗

2022-12-10 17:22 UTC, Cryolitia approved these changes

2022-12-11 02:51 UTC, Rinfair-CSP-A016 approved these changes
@ArtsEpiphany

2022-12-11 07:13 UTC, septs approved these changes

2022-12-13 06:30 UTC, NoiraBaka commented
额…？

2022-12-13 14:32 UTC, NoiraBaka commented
@ArtsEpiphany 喵喵喵？

2022-12-13 14:58 UTC, merged