Merge branch 'main' of https://github.com/mtf-wiki/RLE-wiki into main
mtf-wiki/RLE-wiki pull request #79
Opened 2022-12-11 04:08 UTC by tagbug

2022-12-11 17:37 UTC, Cryolitia requested changes

2022-12-11 17:37 UTC, Cryolitia commented on docs/campus/UJS.md
> +:::
```suggestion

```

2023-01-07 18:30 UTC, ArtsEpiphany reviewed
感谢提交pr！基本没什么问题啦，稍微修改一下就可以合并了呢

2023-01-07 18:30 UTC, ArtsEpiphany commented on docs/campus/UJS.md
> +[江苏大学](https://www.ujs.edu.cn/)（Jiangsu University），位于江苏省镇江市，是江苏省人民政府与中华人民共和国教育部、农业农村部共建的全国重点大学，是“江苏高水平大学建设高峰计划”A类建设高校。
```suggestion
[江苏大学](https://www.ujs.edu.cn)（Jiangsu University，JSU）位于江苏省镇江市，是江苏省人民政府与中华人民共和国教育部、农业农村部共建的全国重点大学，是“江苏高水平大学建设高峰计划”A 类建设高校。
```

2023-01-07 18:30 UTC, ArtsEpiphany commented on docs/campus/UJS.md
> +学校只有一个校区，位于镇江市京口区的郊区（学府路301号），离市区有一定距离，大概坐公交要20分钟到市区，到火车站则要30分钟左右。
```suggestion
学校位于[镇江市京口区学府路 301 号](https://amap.com/place/B01FF02CA4)，离市区有一定距离，大概坐公交要 20 分钟到市区，到火车站则要 30 分钟左右。
```

2023-01-07 18:30 UTC, ArtsEpiphany commented on docs/campus/UJS.md
> +校内的图书馆是花了1个亿造的，所以看起来还不错，平时学习、看书、期末复习都很适合，期末或考研高峰期的时候可能会需要抢位置。各种公共设施也比较完善，教室也都是有空调的。
```suggestion
校内的图书馆是花了 1 个亿造的，所以看起来还不错，平时学习、看书、期末复习都很适合，期末或考研高峰期的时候可能会需要抢位置。各种公共设施也比较完善，教室也都是有空调的。
```

2023-01-07 18:30 UTC, ArtsEpiphany commented on docs/campus/UJS.md
> +江滨医院（江苏大学附属医院）可以进行各种体检（包括激素六项），但价格在没有医保可以使用的情况下比较贵，一次激素六项要花300，加上门诊费用，大概在320左右。医生比较友好，笔者做了在江滨医院做了两次激素六项，医生和护士都没怎么过问。
```suggestion
江滨医院（江苏大学附属医院）可以进行各种体检（包括激素六项），但价格在没有医保可以使用的情况下比较贵，一次激素六项要花 300，加上门诊费用，大概在 320 左右。医生比较友好，笔者做了在江滨医院做了两次激素六项，医生和护士都没怎么过问。
```

2023-01-07 18:30 UTC, ArtsEpiphany commented on docs/campus/UJS.md
> +校内的trans应该很少，笔者知道的只有自己和另一个快毕业的大四学姐。
```suggestion
校内的 trans 应该很少，笔者知道的只有自己和另一个快毕业的大四学姐。 
```

2023-01-08 05:28 UTC, Rinfair-CSP-A016 approved these changes

2023-01-08 05:31 UTC, Cryolitia approved these changes

2023-01-08 05:32 UTC, merged