docs(update): NUIST
mtf-wiki/RLE-wiki pull request #84
Opened 2023-01-23 06:32 UTC by lixiang810

2023-01-23 09:24 UTC, ArtsEpiphany reviewed
感谢提交pr！Arts一会再仔细看看呜呜呜

2023-01-23 09:24 UTC, ArtsEpiphany commented on docs/campus/NUIST.md
> +author: 凌莞 黎想 等
作者多于一人时，建议这样书写
```suggestion
author: 
- 凌莞
- 黎想
- 等
```

2023-01-23 09:24 UTC, ArtsEpiphany commented on docs/campus/NUIST.md
> +校区的分配方式尚不明确，下述内容均指本部。欢迎金牛湖校区的姐妹来补充信息。
```suggestion
::: tip
校区的分配方式尚不明确，下述内容均指本部。欢迎金牛湖校区的姐妹来补充信息。
:::
```

2023-01-23 09:24 UTC, ArtsEpiphany commented on docs/campus/NUIST.md
> +凭加盖医院公章或校医院开具的写明不适宜参加体育运动的证明可以申请保健班（无法直接使用“易性症”证明，[失败案例](https://cdn.lwqwq.com/pic/PE-application-failed-with-medical-record.webp)；如何获取可使用的证明请参考下文），保健班是男女性合班上课的。但貌似也不轻松到哪里去。另外重修也是男女合并的，~~所以，你们也可以像笔者那
也可以这样修改，避免多一个逗号（笑
```suggestion
凭加盖医院公章或校医院开具的写明不适宜参加体育运动的证明可以申请保健班（无法直接使用“易性症”证明，[失败案例](https://cdn.lwqwq.com/pic/PE-application-failed-with-medical-record.webp)；如何获取可使用的证明请参考下文），保健班是男女性合班上课的。但貌似也不轻松到哪里去。另外重修也是男女合并的<del>，所以，你们也可以像笔者那样体育课一次也不去然后直接去重修</del>。
```

2023-01-23 09:24 UTC, ArtsEpiphany commented on docs/campus/NUIST.md
> +学校里面还有个[南气宾馆](https://m.ctrip.com/html5/hotel/hoteldetail/1945120.html)，直通学校。如果家人或者朋友要来南信大参观，可以在那里订房间。南信大学生订房可以有优惠。
请使用桌面版网页链接
```suggestion
学校里面还有个[南气宾馆](https://hotels.ctrip.com/hotels/1945120.html)，直通学校。如果家人或者朋友要来南信大参观，可以在那里订房间。南信大学生订房可以有优惠。
```

2023-01-23 09:31 UTC, lixiang810 commented
![图片](https://user-images.githubusercontent.com/14120445/214006321-953ae50c-05fd-4ada-a827-9602416c31c9.png)

WTF，为啥 gh 的 re-request for review 会这样

2023-01-23 15:40 UTC, Clansty commented on docs/campus/NUIST.md
> +|        项目        |           情况           |
所以这个表格要改回来吗

2023-01-23 15:41 UTC, lixiang810 commented on docs/campus/NUIST.md
> +|        项目        |           情况           |
> 所以这个表格要改回来吗

感觉没必要改，不影响显示的

2023-01-23 16:47 UTC, Cryolitia requested changes

2023-01-23 16:47 UTC, Cryolitia commented on docs/campus/NUIST.md
> +|      宿舍独浴      | ✅（800 一年的没有独卫） |
这里的意思是800一年的独卫和独浴都没有，还是800一年的有独浴没有独卫

2023-01-23 16:47 UTC, Cryolitia commented on docs/campus/NUIST.md
> +军训总体而言较为敷衍，除非你正好碰到一个不敷衍的教官。
```suggestion
> 军训总体而言较为敷衍，除非你正好碰到一个不敷衍的教官。
```

2023-01-23 16:47 UTC, Cryolitia commented on docs/campus/NUIST.md
> +和老师同学不熟，同学给我的感觉还算比较友好的，虽然没怎么接触但是没做什么对我不好的事情。
```suggestion
> 和老师同学不熟，同学给我的感觉还算比较友好的，虽然没怎么接触但是没做什么对我不好的事情。
```

2023-01-23 16:47 UTC, Cryolitia commented on docs/campus/NUIST.md
> +（理科）学生总体而言较为原子化，在不影响他人的前提下，同学一般不会干涉你。我的宿舍有两个宿管阿姨，一个较为严肃，一个和我关系比较好。不过即使是严肃的那个也不会对我怎么样，在我过不了宿舍门禁（人脸识别）时也会帮忙开门。关系好的那个阿姨在放我进去时还会开玩笑：“小美女，今天又进不来啦？”
```suggestion
> （理科）学生总体而言较为原子化，在不影响他人的前提下，同学一般不会干涉你。我的宿舍有两个宿管阿姨，一个较为严肃，一个和我关系比较好。不过即使是严肃的那个也不会对我怎么样，在我过不了宿舍门禁（人脸识别）时也会帮忙开门。关系好的那个阿姨在放我进去时还会开玩笑：“小美女，今天又进不来啦？”
```

2023-01-23 16:49 UTC, lixiang810 commented on docs/campus/NUIST.md
> +|      宿舍独浴      | ✅（800 一年的没有独卫） |
@Clansty

2023-01-24 04:56 UTC, lixiang810 commented on docs/campus/NUIST.md
> +|      宿舍独浴      | ✅（800 一年的没有独卫） |
已解决。

2023-01-24 07:18 UTC, Cryolitia approved these changes

2023-01-26 20:10 UTC, Rinfair-CSP-A016 approved these changes

2023-01-26 20:10 UTC, Rinfair-CSP-A016 commented on docs/campus/NUIST.md
> +|     校医院服务     |          ❌          |
这个空格。。对最终渲染有影响吗。。。（没影响的话感觉没什么加的必要

2023-01-28 07:04 UTC, merged